apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    registry: public.ecr.aws/datadog
    site: datadoghq.com
    tags:
      - env:aurora-staging
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    podLabelsAsTags:
      app: kube_app
      release: helm_release
  features:
    logCollection:
      enabled: true
      containerCollectAll: true

