name: "Workflow - Deploy terrafrom to multy-account AWS environment"
on:
  push:
    branches:
      - "devbranch-michael"
  pull_request:
    branches:
      - staging
      - main

permissions:
  id-token: write
  contents: read

env: 
  AWS_REGION: us-east-1
  ENVIRONMENT_STAGE: ${{ (github.ref == 'refs/heads/main' && 'production') || (github.ref == 'refs/heads/staging' && 'staging') || 'development' }} 


jobs:
  deploy-terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./roots/devops-project-main/
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::601666506652:role/GITHUB-ACTIONS-CICD-ROLE-TEST
          role-session-name: GitHubActionsRoleSession
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
          terraform init -backend-config="bucket=${AWS_ACCOUNT_ID}-state-bucket-${ENVIRONMENT_STAGE}" -backend-config="key=main.tfstate"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false -var-file=${ENVIRONMENT_STAGE}.tfvars

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -input=false -var-file="${ENVIRONMENT_STAGE}.tfvars"