name: "Workflow - Deploy terrafrom to multy-account AWS environment"
on:
  push:
    branches:
      - staging
      - main
      - feature/**

  pull_request:
    branches:
      - staging
      - main

permissions:
  id-token: write
  contents: read

env: 
  AWS_REGION: us-east-1
  ENVIRONMENT_STAGE: ${{ (github.ref == 'refs/heads/main' && 'production') || (github.ref == 'refs/heads/staging' && 'staging') || 'development' }} 


jobs:
  deploy-terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./roots/devops-project-main/
        shell: bash
    
    environment:  ${{ (github.ref == 'refs/heads/main' && 'production') || (github.ref == 'refs/heads/staging' && 'staging') || 'development' }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.MG_ROLE }}
          role-session-name: GitHubActionsRoleSession
          aws-region: ${{ env.AWS_REGION }}


      - name: Assume Role in Target Account
        id: assume_target_account
        run: |
          ROLE_ARN=${{ secrets.CICD_IAM_ROLE }}
          echo $ROLE_ARN
          # Assume the role and capture the output
          ROLE_OUTPUT=$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name GitHubActionsRoleSession)

          # Extract, mask and set credentials as environment variables
          export AWS_ACCESS_KEY_ID=$(echo $ROLE_OUTPUT | jq -r '.Credentials.AccessKeyId')
          export AWS_SECRET_ACCESS_KEY=$(echo $ROLE_OUTPUT | jq -r '.Credentials.SecretAccessKey')
          export AWS_SESSION_TOKEN=$(echo $ROLE_OUTPUT | jq -r '.Credentials.SessionToken')

          echo "::add-mask::$AWS_ACCESS_KEY_ID"
          echo "::add-mask::$AWS_SECRET_ACCESS_KEY"
          echo "::add-mask::$AWS_SESSION_TOKEN"

          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $GITHUB_ENV

          # Verify the credentials are set
          aws sts get-caller-identity

      - name: Terraform Init
        run: |
          aws sts get-caller-identity
          # AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
          terraform init -backend-config="bucket=terraform-state-${ENVIRONMENT_STAGE}-test" -backend-config="key=main.tfstate"

      - name: Terraform Format
        run: terraform fmt

      # - name: Terraform Plan
      #   run: terraform plan -input=false -var-file=${ENVIRONMENT_STAGE}.tfvars

      # - name: Terraform Apply
      #   run: |
      #     terraform apply -auto-approve -input=false -var-file="${ENVIRONMENT_STAGE}.tfvars"

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve -input=false -var-file="${ENVIRONMENT_STAGE}.tfvars"